### ISSUE TITLE
Burger Menu on Landing page

### ISSUE THREAD

**Issue by ralfSDC** [UkraineFirstAid/FirstAidUkraine#37]
- the landing page has a burger menu in the upper left corner
- when clicking on the burger menu it opens
- when the burger menu is opened and I click outside the burger menu it closes again
- when clicking on a item in the burger menu the burger menu closes again
- the burger menu has one entry "imprint" and one entry "home"
- clicking "imprint"  doesn't do anything for now (just close the burger menu again)
- clicking "home" navigates to the landing page
- "imprint" is translated via the "Imprint" key
- "home" is translated via the "Home" key

**Comment by lucasschoenfeld** [comment]
Behaviour:
https://material.io/components/navigation-drawer#modal-drawer
