### ISSUE TITLE
Language selection on landing page

### ISSUE THREAD

**Issue by ralfSDC** [UkraineFirstAid/FirstAidUkraine#38]
- the icon of my currently selected language is shown in the upper right corner
- when I click on a language selection overlay is opened
- The language selected overlay contains all selectable language names translated to my language and the flag of the corresponding country
- if I click on a language selection the language setting is applied to the landing page

**Comment by Seppo007** [comment]
Language selector introduced | CSS Arrangement completed | functionality (dropdown, choosing) missing

**Comment by sebastiankutschbach** [comment]
added functionality. issue resolved
